services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
#     volumes:
#         - localstack-data:/tmp/localstack
#         # - /var/run/docker.sock:/var/run/docker.sock  # 必要に応じてコメントアウト

# volumes:
#   localstack-data:

services:
